name: kardec_digital
description: "Uma biblioteca digital com livros espiritas"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  firebase_storage: ^12.4.8
  cloud_firestore: ^5.4.4
  file_picker: ^8.1.2
  flutter_pdfview: ^1.2.0
  http: ^1.1.0
  path_provider: ^2.0.0
  logger: ^2.0.2+1
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  shimmer: ^2.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner.jpg