// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8jHzVIeFfP1jJepFWs0E33UAoQktBkPM',
    appId: '1:879734462680:web:0b67fd9ecd6b411efe5fad',
    messagingSenderId: '879734462680',
    projectId: 'kardec-digital',
    authDomain: 'kardec-digital.firebaseapp.com',
    storageBucket: 'kardec-digital.firebasestorage.app',
    measurementId: 'G-K34G88ZS5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtQvVIirhO1YbhMpLogjhDvpIMPzKQWgI',
    appId: '1:879734462680:android:60387c63a4cda6ddfe5fad',
    messagingSenderId: '879734462680',
    projectId: 'kardec-digital',
    storageBucket: 'kardec-digital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUKAg5v0tZKAMwCizUxV312eQ9RHGZNbA',
    appId: '1:879734462680:ios:f10d7a8ac215df29fe5fad',
    messagingSenderId: '879734462680',
    projectId: 'kardec-digital',
    storageBucket: 'kardec-digital.firebasestorage.app',
    iosBundleId: 'br.com.jaff.biblioteca.kardec.kardecDigital',
  );
}
